console.log('This is log message')
console.info('This is infor message')
console.error('this is an error')
console.warn('this is warning from console')
console.table({name:"santanu", city:"Bhubaneswar"})